# Generated by Django 5.0.7 on 2024-10-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_address_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='adress_type',
            new_name='address_type',
        ),
    ]
