# Generated by Django 5.0.7 on 2024-10-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_adress_type_address_address_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
